### ISSUE TITLE
Tweak standard race variables?

### ISSUE THREAD

**Issue by timhendo** [CoryMcCartan/PL94171#1]
Has anyone forked or tweaked in on order to change 'standard' race variables? I need total race numbers alone or in combination and including Hispanic, rather than the one-race non-Hispanic variables here
https://corymccartan.github.io/PL94171/reference/pl_select_standard.html

**Comment by CoryMcCartan** [comment]
Hello—
If you need access to variables other than those selected by `pl_select_standard()`, you may just omit that function from your pipeline and access the variables directly using the PXXXYYYY syntax, where XXX is the table and YYYY is the variable, once you have called `pl_subset()`. All that `pl_select_standard()` does is call `select()` and optionally rename the resulting variables.
P.L. 94-171 file variable documentation can be found [here](https://www2.census.gov/programs-surveys/decennial/2020/technical-documentation/complete-tech-docs/summary-file/2020Census_PL94_171Redistricting_NationalTechDoc.pdf#page=54).

**Comment by timhendo** [comment]
Very helpful thanks (and thanks for this very useful package )
